services:
  - type: web
    name: menu-api
    env: java
    plan: starter  # Ücretsiz plan, ihtiyaca göre değiştirebilirsin
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/appmenu-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
